// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SALGADBLib;

namespace SALGADBLib.Migrations
{
    [DbContext(typeof(SALGADbContext))]
    [Migration("20210303144116_AddedServiceOptions")]
    partial class AddedServiceOptions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SALGADemographics.HRMDFunctionDemographics", b =>
                {
                    b.Property<int>("pkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CorporateService")
                        .HasColumnType("bit");

                    b.Property<int>("NoPeople")
                        .HasColumnType("int");

                    b.Property<byte[]>("Organogram")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OrganogramFileFormat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pkID");

                    b.ToTable("HRMDFunctionDemographics");
                });

            modelBuilder.Entity("SALGADemographics.IntervieweeDetails", b =>
                {
                    b.Property<int>("pkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JobTitlepkID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsInPosition")
                        .HasColumnType("int");

                    b.HasKey("pkID");

                    b.HasIndex("JobTitlepkID");

                    b.ToTable("IntervieweeDetails");
                });

            modelBuilder.Entity("SALGADemographics.JobTitle", b =>
                {
                    b.Property<int>("pkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pkID");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("SALGADemographics.Municipality", b =>
                {
                    b.Property<int>("pkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pkID");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("SALGADemographics.MunicipalityDemographics", b =>
                {
                    b.Property<int>("pkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NoEmployees")
                        .HasColumnType("int");

                    b.Property<int>("NoFixedTerm54A56")
                        .HasColumnType("int");

                    b.Property<int>("NoFixedTermNon54A56")
                        .HasColumnType("int");

                    b.Property<int>("NoOther")
                        .HasColumnType("int");

                    b.Property<int>("NoPerm54A56")
                        .HasColumnType("int");

                    b.Property<int>("NoPermNon54A56")
                        .HasColumnType("int");

                    b.Property<byte[]>("Organogram")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OrganogramFileFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMonthlyPayroll")
                        .HasColumnType("int");

                    b.HasKey("pkID");

                    b.ToTable("MunicipalityDemographics");
                });

            modelBuilder.Entity("SALGADemographics.ServiceOption", b =>
                {
                    b.Property<int>("pkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pkID");

                    b.ToTable("ServiceOptions");
                });

            modelBuilder.Entity("SALGADemographics.IntervieweeDetails", b =>
                {
                    b.HasOne("SALGADemographics.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitlepkID");

                    b.Navigation("JobTitle");
                });
#pragma warning restore 612, 618
        }
    }
}
